project_id = "lqjnwjowbcptkucnpptb"

[functions.send-notification]
verify_jwt = false

[functions.didit-verification]
verify_jwt = false

[functions.generate-certificate]
verify_jwt = false

[functions.send-invitation]
verify_jwt = false

[functions.send-owner-invitation]
verify_jwt = false